name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./split.sh
